#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --time=6:00:00
#SBATCH --mem=10GB
#SBATCH --job-name=dcgan
#SBATCH --mail-type=END
#SBATCH --mail-user=ls4411@nyu.edu
#SBATCH --output=dcgan_\%j.out

module purge
module load pytorch/intel/20170226
module load torchvision/0.1.7

cd /scratch/ls4411/Research/GAN/QualityAssessor

DIR_NAME="ac-w-gan-max_normalize_c01"
FILE_NAME="ac-w-gan-normalize"

mkdir ../TrainedNetworks/$DIR_NAME

python main.py --c=0.01 --epochs=100 --Wasserstein=True --clamp=True --dataset=mnist --imageSize=28 --cuda --n-critic=5 --ac-gan=True --name=/$DIR_NAME/$FILE_NAME --clamping-method=max_normalize &> /scratch/ls4411/Research/GAN/TrainedNetworks/$DIR_NAME/$FILE_NAME-output.txt

exit 0

## Empty line
