#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --time=24:00:00
#SBATCH --mem=10GB
#SBATCH --job-name=dcgan
#SBATCH --mail-type=END
#SBATCH --mail-user=ls4411@nyu.edu
#SBATCH --output=dcgan_\%j.out

module purge
module load pytorch/intel/20170226
module load torchvision/0.1.7

cd /scratch/ls4411/Research/GAN/QualityAssessor

python main.py --dataset=mnist --imageSize=28 --cuda --name=wgan --Wasserstein=True --n-critic=5 --clamp=True &> /scratch/ls4411/Research/job-output/wgan-mnist.txt

exit 0

## Empty line
